spring:
  application:
    name: Products Api
  datasource:
    url: jdbc:h2:file:C:/Users/Gustavo Rodrigues/test;AUTO_SERVER=TRUE
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console